### ISSUE TITLE
I can’t push to the `fortify` branch anymore

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-webgoat#156]
@mkurz I'm guessing there was some kind of permissions cleanup and I was an accidental victim?

**Comment by mkurz** [comment]
Should be resolved now

**Comment by SethTisue** [comment]
indeed, thank you!

**Comment by SethTisue** [comment]
@mkurz I have a new problem, which is that on the `fortify` branch GitHub Actions needs a secret to run; the secret that is in place has expired, resulting in the failures seen at https://github.com/playframework/play-webgoat/actions/runs/10148636531 ; and I no longer have the necessary access to update the secret

**Comment by mkurz** [comment]
@SethTisue Try again.

**Comment by SethTisue** [comment]
@mkurz I was able to update the secret, and https://github.com/playframework/play-webgoat/actions/runs/10148636531 went green on re-run

thank you!
