### ISSUE TITLE
move to playframework org?

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-webgoat#2]
@gmethvin I don't know why this didn't occur to me before, but perhaps this would more logically be under the playframework org than the lightbend org?

**Comment by SethTisue** [comment]
@marcospereira ?

**Comment by marcospereira** [comment]
It makes sense to me. I don't have the rights to make it happen though.

**Comment by SethTisue** [comment]
@marcospereira I think you should have the necessary rights now

**Comment by marcospereira** [comment]
Done! 👍

**Comment by marcospereira** [comment]
By the way, a good thing here is that we can now keep this updated with Play releases. ;-)

**Comment by SethTisue** [comment]
cool. this is _the_ repo we use to demo Fortify SCA for Scala, btw, and for testing too
