### ISSUE TITLE
Mergify configuration is invalid on 2.8.x branch

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-webgoat#52]
I'm seeing this in every PR; an example is https://github.com/playframework/play-webgoat/pull/50

@mkurz is there a standard playframework/* Mergify configuration I can pull in from somewhere that doesn't have this problem?

btw this repo is of concern to me because it's one of our sample repos for https://developer.lightbend.com/docs/fortify/current

**Comment by mkurz** [comment]
Fixed by #54
Just two days ago I opened a PR so we can put a master mergify config in our orgs `.github` repo: https://github.com/Mergifyio/mergify-engine/pull/4050 
Let's see how this works out.
